### ISSUE TITLE
Error compiling net/wifibox-alpine from ports in FreeBSD 12.3

### ISSUE THREAD

**Issue by maurizio-emmex** [pgj/freebsd-wifibox-alpine#1]
Hi, I want to use wifibox for using a Broadcom BCM4331 802.11a/b/g/n wifi device on a 2012 Mac Mini running FreeBSD 12.3-RELEASE-p5.
After upgrading the ports directory
> sudo portsnap auto
> cd /usr/ports/net/wifibox-alpine
> sudo make config
and selecting only FW_BRCM          Broadcom 802.11n
Running
> sudo make 
I have this error:
...
/usr/local/bin/patchelf  --set-interpreter /usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/bootstrap/lib/ld-musl-x86_64.so.1  /usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/bootstrap/sbin/apk
/usr/bin/brandelf -t Linux /usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/bootstrap/sbin/apk
/usr/local/bin/patchelf  --set-interpreter /usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/bootstrap/lib/ld-musl-x86_64.so.1  /usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/bootstrap/bin/busybox
/usr/bin/brandelf -t Linux /usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/bootstrap/bin/busybox
/usr/bin/env LD_LIBRARY_PATH=/usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/bootstrap/lib  /usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/bootstrap/sbin/apk add  --initdb  --no-network  --no-cache  --force-non-repository  --allow-untrusted  --no-progress  --clean-protected  --root /usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/image-contents  --no-scripts  --no-chown  /usr/ports/distfiles/wifibox-alpine/baselayout-3.2.0-r18.apk /usr/ports/distfiles/wifibox-alpine/busybox-1.34.1-r5.apk /usr/ports/distfiles/wifibox-alpine/ifupdown-ng-0.11.3-r0.apk /usr/ports/distfiles/wifibox-alpine/iptables-1.8.7-r1.apk /usr/ports/distfiles/wifibox-alpine/iw-5.16-r0.apk /usr/ports/distfiles/wifibox-alpine/libcrypto1.1-1.1.1n-r0.apk /usr/ports/distfiles/wifibox-alpine/libmnl-1.0.4-r2.apk /usr/ports/distfiles/wifibox-alpine/libnftnl-1.2.1-r0.apk /usr/ports/distfiles/wifibox-alpine/libnl3-3.5.0-r0.apk /usr/ports/distfiles/wifibox-alpine/libssl1.1-1.1.1n-r0.apk /usr/ports/distfiles/wifibox-alpine/linux-lts-5.15.36-r0.apk /usr/ports/distfiles/wifibox-alpine/musl-1.2.2-r7.apk /usr/ports/distfiles/wifibox-alpine/openrc-0.44.7-r5.apk /usr/ports/distfiles/wifibox-alpine/pcsc-lite-libs-1.9.4-r0.apk /usr/ports/distfiles/wifibox-alpine/socat-1.7.4.2-r0.apk /usr/ports/distfiles/wifibox-alpine/wpa_passthru-0.1.1-r0.apk /usr/ports/distfiles/wifibox-alpine/wpa_supplicant-2.9-r17.apk
ELF binary type "3" not known.
/usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/bootstrap/sbin/apk: 1: Syntax error: ")" unexpected
*** [/usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df/work/image-contents/.done] Error code 2

make[2]: stopped in /usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df
1 error

make[2]: stopped in /usr/ports/net/wifibox-alpine/work-default/freebsd-wifibox-alpine-dac84c054786b6eb6f329662748d9a199b05f2df
===> Compilation failed unexpectedly.
Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
the maintainer.
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/net/wifibox-alpine
*** Error code 1

Stop.
make: stopped in /usr/ports/net/wifibox-alpine
--
Regards
Maurizio

**Comment by pgj** [comment]
Looks like the Linuxulator is not activated.  Did you have the `linux64` kernel module loaded?  This is how you can check it:

~~~{.console}
# kldstat -n linux64
~~~

If not, you can do that by the following command:

~~~{.console}
# kldload linux64
~~~

**Comment by pgj** [comment]
Added an explicit check for `linux64` in https://github.com/pgj/freebsd-wifibox-port/commit/572128bb70e1dd5511d20da11336c4b672397e3a which could catch such problems in the future.

**Comment by pgj** [comment]
Documented the dependency on the Linuxulator in https://github.com/pgj/freebsd-wifibox-alpine/commit/a6085330a18c8a257d2e185aab016c483335f86a .

**Comment by maurizio-emmex** [comment]
Thank you, after loading the `linux64` kernel module I can compile the port.
